name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: notification-utils:latest
          outputs: type=docker,dest=/tmp/notification-utils.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Cache image
        id: notif-utils-docker
        uses: actions/cache@v3
        with:
          path: /tmp/notification-utils.tar
          key: ${{ github.sha }}-utils
  lint-black:
    name: "Python linting: Black"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-utils.tar
          key: ${{ github.sha }}-utils
      - run: docker load --input /tmp/notification-utils.tar
      - run: docker run --rm notification-utils:latest make lint-black
  lint-flake:
    name: "Python linting: Flake"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-utils.tar
          key: ${{ github.sha }}-utils
      - run: docker load --input /tmp/notification-utils.tar
      - run: docker run --rm notification-utils:latest make lint-flake
  order-check:
    name: Check imports order
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-utils.tar
          key: ${{ github.sha }}-utils
      - run: docker load --input /tmp/notification-utils.tar
      - run: docker run --rm notification-utils:latest make order-check
  unit-tests:
    name: Python unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/notification-utils.tar
          key: ${{ github.sha }}-utils
      - run: docker load --input /tmp/notification-utils.tar
      - run: docker run --rm notification-utils:latest make unit-tests
